### PR TITLE
Change Object_ID reference in az query

### PR DESCRIPTION
**Pull request by m-rajagopal**
# [Issue-id](https://github.com/Azure/caf-terraform-landingzones/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] My code follows the code style of this project.
- [ ] I ran lint checks locally prior to submission.
- [X] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

This PR updates

the 'Object_ID' reference to 'id' in az query in YAML file to support the latest AZ CLI version
caf_landingzone_branch variable to 2203.2 to generate updated readme.md file pointing to latest branch

## Does this introduce a breaking change

- [ ] YES
- [X] NO

### CODE REVIEW

**Review by florianow — APPROVED** [review]
line 6 in the walktrough.yml changed by azure cli. I confirm the change

**Comment by florian-ried** [comment]
Works for me :) Thank you very much!

**Review by LaurentLesle — APPROVED** [review]
LGTM

**Comment by LaurentLesle** [comment]
Fixed in 5.6.8

**Pull request closed without merging**
