### PR TITLE
Feature: a new addon to support aks private cluster usecases

### PR DESCRIPTION
**Pull request by najvv**
## PR Checklist

---

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code follows the code style of this project.
- [x] I ran lint checks locally prior to submission.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

AKS addon with exec plugin authentication. Provide some necessary tools to perform cluster configuration.

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing
example files are provided

### CODE REVIEW

**Comment by najvv** [comment]
@microsoft-github-policy-service agree

**Review by LaurentLesle — CHANGES_REQUESTED** [review]
Very good PR. Can you also add one folder with an example we can add in the ci to test all the components

**Comment by najvv** [comment]
@LaurentLesle thank you for the feedback. I have added an example set. let me know if you want me to add aks cluster config in aztfmod repo.

**Comment by najvv** [comment]
@LaurentLesle thank you for the feedback. I have added an example set. let me know if you want me to add aks cluster config in aztfmod repo.

**Comment by arnaudlh** [comment]
thanks for your contribution @najvv!

**Pull request merged**
